---
title: About My Research in < 500 Words
author: Matt Higham
date: '2018-09-22'
slug: why-research
categories: []
tags: []
header:
  caption: ''
  image: ''
---

I have focused on applied problems in the ecological sciences primarily involving \textbf{population size prediction} and \textbf{spatial sampling}. I began my PhD research career working on population size prediction of moose in Togiak, Alaska, with grant support from the Alaska Fish and Wildlife Service. The challenge in many of these ecological studies is that not all individuals are detected, giving rise to capture-recapture methods, distance sampling methods, removal sampling, and methods involving direct modeling of imperfect detection (which is the area that I work in). The following flowchart summarizes many of the issues and components with predicting a population total in ecology. The orange denotes quantities from the spatial model, blue denotes quantities from the detection model, and green denotes quantities that are a function of both the spatial model and the detection model. Shape indicates whether we observe the quantity or not, with rectangles denoting observed data and ellipses denoting unobserved quantities. The flow chart was made using the `diagram` package in `R`.

```{r, echo = FALSE, include = TRUE, cache = TRUE, fig.height = 2.5, fig.width = 4.5, results = 'hide', warning = FALSE, message = FALSE}

library(diagram)
library(ggplot2); library(scales)
library(ggthemes)

#E69F00
#56B4E9
#009E73

par(mar = c(1, 1, 1, 1))
openplotmat()

## generates the arrows
elpos <- coordinates(c(1, 1, 2, 4))
elpos <- elpos
elpos[1, ] <- c(0.250, 0.875)
elpos[2, ] <- c(0.750, 0.875)
elpos[3, ] <- c(0.5, 0.75)
elpos[4, ] <- c(0.5, 0.4)
elpos[5, ] <- c(0.5, 0.1)
elpos[6, ] <- c(0.1, 0.4)
elpos[7, ] <- c(0.1, 0.1)
elpos[8, ] <- c(0.75, 0.4)



fromto <- matrix(ncol = 2, byrow = TRUE,
  data = c(2, 3, 2, 4, 4, 7, 4, 8))
 nr <- nrow(fromto)
 arrpos <- matrix(ncol = 2, nrow = nr)
 #3for (i in 1:nr) {
  ##arrpos[i, ] <- straightarrow (to = elpos[fromto[i, 2], ],
  ##   from = elpos[fromto[i, 1], ],
  ##   lwd = 2, arr.pos = 0.6, arr.length = 0.5)
 ##}
 
 straightarrow(from = elpos[fromto[1, 1], ], to = elpos[fromto[1, 2], ], lty = 1, lcol = 1)
straightarrow(from = elpos[1, ], to = elpos[2, ], lty = 1, lcol = 1,
  arr.pos = 0.1)
text(0.5, 0.93, labels = "OR")
 straightarrow(from = elpos[1, ], to = elpos[3, ], lty = 1, lcol = 1)
 straightarrow(from = elpos[2, ], to = elpos[3, ], lty = 1, lcol = 1)
 straightarrow(from = elpos[3, ], to = elpos[4, ], lty = 1, lcol = 1)
 straightarrow(from = elpos[4, ], to = elpos[5, ], lty = 1, lcol = 1)
 straightarrow(from = elpos[6, ], to = elpos[5, ], lty = 1, lcol = 1)
 straightarrow(from = elpos[6, ], to = elpos[7, ], lty = 1, lcol = 1)
 straightarrow(from = elpos[3, ], to = elpos[8, ], lty = 1, lcol = 1)

 ## generates top box 
 textellipse(elpos[1, ], 0.1, lab = "Geostat", box.col = "#E69F00",
   shadow.col = "darkorange", shadow.size = 0.005, cex = 0.75,
   radx = 0.09, rady = 0.06)
 textellipse(elpos[2, ], 0.1, lab = "CAR", box.col = "#E69F00",
   shadow.col = "darkorange", shadow.size = 0.005, cex = 0.75,
   radx = 0.09, rady = 0.06)
 textellipse(elpos[3, ], 0.1, lab = c("Spatial", "Surface"), box.col = "#E69F00",
   shadow.col = "darkorange", shadow.size = 0.005, cex = 0.75, 
   radx = 0.07)
 textellipse(elpos[4, ], 0.1, lab = c("`True`", "Counts"), box.col = "#E69F00",
   shadow.col = "darkorange", shadow.size = 0.005, cex = 0.75,
   radx = 0.07)
 textrect(elpos[5, ], 0.15, 0.075, lab = c("Observed", "Counts"), box.col = "#009E73",
   shadow.col = "darkgreen", shadow.size = 0.005, cex = 0.75)
 
 textellipse(elpos[6, ], 0.1, lab = "Detection", box.col = "#56B4E9",
   shadow.col = "darkblue", shadow.size = 0.005, cex = 0.75, col = "black")
 textrect(elpos[7, ], 0.1, 0.075, lab = c("Sightability", "Data"),
   box.col = "#56B4E9",
   shadow.col = "darkblue", shadow.size = 0.005, cex = 0.75)
 textellipse(elpos[8, ], 0.1, lab = c("Unsampled", "Site Counts"), box.col = "#E69F00",
   shadow.col = "darkorange", shadow.size = 0.005, cex = 0.75, 
   radx = 0.10)
```

One reason this area of research is particularly interesting is that it is not immediately obvious how to incorporate both the uncertainty in estimating detection and the uncertainty in predicting counts on unobserved sites. A Bayesian approach fits nicely into this hierarchical framework, but, there is a trade-off in computation time. Additionally, these imperfect detection models are used by wildlife biologists in many different settings, and Bayesian models need to be implemented and monitored a bit more carefully. 