---
title: Online Teaching
author: Matt Higham
date: '2018-01-11'
slug: online-teaching
categories: []
tags: []
header:
  caption: ''
  image: ''
---

In the Fall of 2017, I was assigned to teach ST 202D, an introductory statistics course through Oregon State's Ecampus. Through this opportunity, I learned how to better serve as an instructor in this non-traditional teaching setting. At the time of teaching the class, I had never actually taken or instructed an online class. I found that there were many similarities between the less traditional online teaching setting and the more traditional face-to-face courses, but that there were also significant differences between teaching in the two media (similarly, I found some commonalities and important differences between coaching a high school sport and teaching face-to-face courses at a university but that can be the topic for a future post!) In this post, I want to briefly consider some of my perceived differences between online teaching and face-to-face teaching in the following mini-online teaching philosophy. For my own reflection, I found it helpful to break online teaching into three components: **student-content**, **student-instructor**, and **student-student** interactions.

Even though online statistics courses and face-to-face statistics courses often have the same learning outcomes, simply copying elements of a face-to-face course to an online course might not be the most effective approach. But what needs to be modified and in what ways? Both face-to-face courses and online courses involve **student-content**, **student-instructor**, and **student-student** interaction, but the way that these interactions are set-up and executed can make a big difference in the success of an online statistics course.

**Student-content** interactions are a vital component in online courses. Students are often initially quite nervous to take a statistics course and may be even more nervous that the course is online. Taking advantage of multimedia content across the Internet and making sure that the course is well-organized and easy to navigate are a couple of strategies that can make student-content interactions more pleasant and less intimidating.

One aspect in which **student-instructor** interactions differ in online courses is in the building of rapport between the instructor and students. Unlike online courses, face-to-face courses allow students to easily see the instructor in a class setting. One way to build rapport is to simply send a welcome video at the start of the term including some relatable instructor background. Additionally, instructor-student communication via text or email can sometimes feel cold, particularly when the instructor is suggesting improvement on a particular assignment. Therefore, I am a proponent of introducing some less formal communication styles on assignment feedback, including incorporating audio or video feedback if necessary and using positive enthusiasm in written feedback.

Discussion boards are one tool used to facilitate **student-student** interactions and can be combined with other online teaching concepts like active learning and metacognition. For example, students might be asked to write a few practice exam questions and to also answer another student’s questions, increasing quality student-student interaction while also creating space for students to perform a metacognitive activity. An instructor can contribute here and there to these student-focused discussion boards so that students feel an instructor presence throughout the quarter. However, I believe that the instructor’s role should be no more than a facilitator so as not to turn these discussions from student-student focused to student-instructor focused.

With the explosion of online education in the past decade come new and exciting challenges. Students in online statistics courses can potentially feel intimidated and lonely, but they do not have to feel that way! Having a well-organized course, building rapport early, and increasing peer-peer interactions can allow students to feel comfortable and engaged. We should embrace new challenges in online learning, remembering that an online course need not and should not be an exact replicate of a face-to-face course.